# Generated by Django 2.2.10 on 2020-09-30 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=500)),
                ('videoId', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField()),
                ('thumbnail', models.CharField(max_length=200)),
                ('channelId', models.CharField(max_length=200)),
                ('channelTitle', models.CharField(max_length=200)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='search.Query')),
            ],
        ),
    ]
